apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-postgres-service
  labels: {{- toYaml .Values.labels.db.global | nindent 4 }}
spec:
  type: {{ .Values.service.db.type }}
  ports:
    - port: {{ .Values.service.db.sourcePort }}
      targetPort: {{ .Values.service.db.targetPort }}
      protocol: TCP
      name: http
  selector: {{- toYaml .Values.labels.db.global | nindent 4 }}
