# NOTE: the name cannot have underscore
name: abd-vro
owner: VA-OCTO
environment: dev # The .Values.environment is computed by the deploy plugin - it returns//uses values like dev, qa, pre, prod etc
cluster: nonprod
# TODO: How is version used? What should this be set to?
version: 0.1

labels:
  redis:
    global: &labels-redis-global
      app: redis-cache
    pod:
      <<: *labels-redis-global
      sidecar.istio.io/inject: "false"

resources:
  redis:
    requests:
      cpu: 150m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

service:
  redis:
    type: ClusterIP
    sourcePort: 6379
    targetPort: 6379
  mq:
    type: ClusterIP
    sourcePort: 5672
    targetPort: 5672

volumes:
  tracking:
    name: tracking-persistent-storage
    claimName: tracking-efs-claim
    mountPath: /persist/tracking

redis:
  secretName: redis
  passwordKey: redisPassword
