# This file is used by the dockerRun Gradle task.
# Note `spring.profiles.include=docker` in buildSrc/README.md#starterjavacontainer-conventionsgradle

spring:
  datasource:
    url: jdbc:h2:mem:example;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS example\;SET SCHEMA example;
    username: skuser
    password: localT3st!
    hikari:
      jdbc-url: jdbc:h2:mem:example;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS example\;SET SCHEMA example;
      username: skuser
      password: localT3st!
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org.springframework.jdbc.core: INFO # DEBUG
    org.springframework.jdbc.core.JdbcTemplate: INFO # DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: INFO # TRACE
    org.hibernate.SQL: INFO # DEBUG
    org.type.descriptor.sql.BasicBinder: INFO # TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: INFO # TRACE
