version: '3.9'

networks:
  internal:

services:
  vro-api-rabbit-mq-service:
    image: rabbitmq:3
    hostname: vro-api-rabbit-mq-service
    expose:
      - "5672"
    ports:
      - "5672:5672"
    networks:
      - internal

  redis:
    image: redis
    hostname: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
    networks:
      - internal

  pdfgenerator:
    container_name: pdfgenerator
    environment:
      RABBITMQ_PLACEHOLDERS_HOST: vro-api-rabbit-mq-service
      RABBITMQ_PLACEHOLDERS_USERNAME: guest
      RABBITMQ_PLACEHOLDERS_USERPASSWORD: guest
      REDIS_PLACEHOLDERS_HOST: vro-api-redis-service
    ports:
      - "5000:5000"
    networks:
      - internal
