apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-app
  labels: {{- toYaml .Values.labels.api | nindent 4 }}
  annotations:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/version: {{ .Values.version | quote }}
    app.kubernetes.io/owner: {{ .Values.owner }}
    app.kubernetes.io/env: {{ .Values.environment }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- toYaml .Values.labels.api | nindent 6 }}
  template:
    metadata:
      labels: {{- toYaml .Values.labels.api | nindent 8 }}
      annotations:
        app.kubernetes.io/podname: {{ .Values.name }}
        app.kubernetes.io/podversion: {{ .Values.version | quote }}
        app.kubernetes.io/podowner: {{ .Values.owner }}
        app.kubernetes.io/podenv: {{ .Values.environment }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.name }}-ghcr
      volumes:
        - name: {{ .Values.volumes.tracking.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.tracking.claimName }}
      initContainers:
        - name: pg-isready
          # TODO: This simple container does not need to use the big `db` image
          image: {{ .Values.images.registry }}/{{ .Values.images.org }}/{{ .Values.images.repo }}/{{ .Values.images.db.imageName }}:{{ .Values.images.db.tag }}
          env:
            - name: ENV
              value: {{ .Values.environment }}
            - name: POSTGRES_FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbinit.secretName }}
                  key: {{ .Values.dbinit.usernameKey }}
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: {{ .Values.postgres.dbnameKey }}
          command:
            - /bin/sh
            - -c
            - |
              /bin/sh -c "
                until pg_isready -d $POSTGRES_DB -h {{ .Chart.Name }}-postgres-service -p {{ .Values.service.db.targetPort}} -U $POSTGRES_FLYWAY_USER; do
                  echo 'Waiting for Postgres DB to be available'
                  sleep 5
                done
              "
          resources: {{- toYaml .Values.resources.pgIsReady | nindent 12 }}
        - name: db-init
          image: {{ .Values.images.registry }}/{{ .Values.images.org }}/{{ .Values.images.repo }}/{{ .Values.images.dbInit.imageName }}:{{ .Values.images.dbInit.tag }}
          env:
            - name: ENV
              value: {{ .Values.environment }}
            - name: FLYWAY_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbinit.secretName }}
                  key: {{ .Values.dbinit.urlKey }}
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbinit.secretName }}
                  key: {{ .Values.dbinit.usernameKey }}
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbinit.secretName }}
                  key: {{ .Values.dbinit.passwordKey }}
            - name: FLYWAY_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: {{ .Values.postgres.schemaKey }}
            - name: FLYWAY_PLACEHOLDERS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: {{ .Values.postgres.usernameKey }}
            - name: FLYWAY_PLACEHOLDERS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: {{ .Values.postgres.dbnameKey }}
            - name: FLYWAY_PLACEHOLDERS_SCHEMA_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: {{ .Values.postgres.schemaKey }}
            - name: FLYWAY_PLACEHOLDERS_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: {{ .Values.postgres.passwordKey }}
          resources: {{- toYaml .Values.resources.api | nindent 12 }}
      containers:
        - name: {{ .Values.name }}-api
          image: {{ .Values.images.registry }}/{{ .Values.images.org }}/{{ .Values.images.repo }}/{{ .Values.images.app.imageName }}:{{ .Values.images.app.tag }}
          ports: {{- toYaml .Values.ports | nindent 10 }}
          livenessProbe: {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe: {{- toYaml .Values.readinessProbe | nindent 12 }}
          env:
            - name: ENV
              value: {{ .Values.environment }}
            - name: apiAuthKey01
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.api.apiKeySecret}}
                  key: {{ .Values.api.apiKey01 }}
            - name: apiAuthKey02
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.api.apiKeySecret}}
                  key: {{ .Values.api.apiKey02 }}
            - name: LH_API_AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: {{ .Values.dataservice.lhApiAuthUrl }}
            - name: SLACK_EXCEPTION_CHANNEL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: {{ .Values.dataservice.slackExceptionChannel }}
            - name: SLACK_EXCEPTION_WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: {{ .Values.dataservice.slackExceptionWebhook }}
            - name: VRO_AUD_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: {{ .Values.dataservice.vroAudUrl }}
            - name: LH_VRO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: {{ .Values.dataservice.lhVroApiKey }}
            - name: VALIDATE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: {{ .Values.dataservice.validateToken }}
            - name: JAVA_OPTS
              value: -Xmx512m
            - name: PERSIST_TRACKING_FOLDER
              value: {{ .Values.volumes.tracking.mountPath }}
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: {{ .Values.postgres.urlKey }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: {{ .Values.postgres.usernameKey }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: {{ .Values.postgres.passwordKey }}
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: {{ .Values.postgres.dbnameKey }}
            - name: POSTGRES_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: {{ .Values.postgres.schemaKey }}
            - name: SERVER_SERVLET_CONTEXTPATH
              value: /{{ .Values.name }}-orig
            - name: STARTER_OPENAPI_SERVERURL
              value: /{{ .Values.name }}-orig
            - name: RABBITMQ_PLACEHOLDERS_HOST
              value: {{ .Chart.Name }}-rabbit-mq-service
            - name: RABBITMQ_PLACEHOLDERS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitmq.secretName }}
                  key: {{ .Values.rabbitmq.usernameKey }}
            - name: RABBITMQ_PLACEHOLDERS_USERPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitmq.secretName }}
                  key: {{ .Values.rabbitmq.passwordKey }}
            - name: REDIS_PLACEHOLDERS_HOST
              value: {{ .Chart.Name }}-redis-service
            - name: REDIS_PLACEHOLDERS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.secretName }}
                  key: {{ .Values.redis.passwordKey }}
            - name: MAS_API_AUTH_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mas.keyName }}
                  key: {{ .Values.mas.masApiAuthClientId }}
            - name: MAS_API_AUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mas.keyName }}
                  key: {{ .Values.mas.masApiAuthClientSecret }}
            - name: MAS_API_AUTH_SCOPE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mas.keyName }}
                  key: {{ .Values.mas.masApiAuthScope }}
            - name: MAS_API_AUTH_TOKEN_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mas.keyName }}
                  key: {{ .Values.mas.masApiAuthTokenUri }}
            - name: MAS_API_BAS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mas.keyName }}
                  key: {{ .Values.mas.masApiBaseUrl }}
            - name: MAS_COLLECTION_ANNOTS_PATH
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mas.keyName }}
                  key: {{ .Values.mas.masCollectionAnnotsPath }}
            - name: MAS_COLLECTION_STATUS_PATH
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mas.keyName }}
                  key: {{ .Values.mas.masCollectionStatusPath }}
            - name: MAS_CREATE_EXAM_ORDER_PATH
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mas.keyName }}
                  key: {{ .Values.mas.masCreateExamOrderPath }}

            - name: BIP_APPLICATION_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bip.keyName }}
                  key: {{ .Values.bip.bipApplicationId }}
            - name: BIP_APPLICATION_ISS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bip.keyName }}
                  key: {{ .Values.bip.bipApplicationIss }}
            - name: BIP_CLAIM_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bip.keyName }}
                  key: {{ .Values.bip.bipClaimSecret }}
            - name: BIP_CLAIM_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bip.keyName }}
                  key: {{ .Values.bip.bipClaimUrl }}
            - name: BIP_CLAIM_USERID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bip.keyName }}
                  key: {{ .Values.bip.bipClaimUserId }}
            - name: BIP_EVIDENCE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bip.keyName }}
                  key: {{ .Values.bip.bipEvidenceSecret }}
            - name: BIP_EVIDENCE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bip.keyName }}
                  key: {{ .Values.bip.bipEvidenceUrl }}
            - name: BIP_EVIDENCE_USERID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bip.keyName }}
                  key: {{ .Values.bip.bipEvidenceUserId }}
            - name: BIP_STATION_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bip.keyName }}
                  key: {{ .Values.bip.bipStationId }}
            - name: BIP_KEYSTORE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bip.keyName }}
                  key: {{ .Values.bip.bipKeyStore }}
            - name: BIP_TRUSTSTORE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bip.keyName }}
                  key: {{ .Values.bip.bipTrustStore }}
            - name: BIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bip.keyName }}
                  key: {{ .Values.bip.bipPassword }}
            - name: BIP_ALIAS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bip.keyName }}
                  key: {{ .Values.bip.bipAlias }}
          resources:
            requests:
              cpu: 150m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          volumeMounts:
            - name: {{ .Values.volumes.tracking.name }}
              mountPath: {{ .Values.volumes.tracking.mountPath }}
