version: "3.6"

services:
  vro-api-rabbit-mq-service:
    image: rabbitmq:3
    hostname: vro-api-rabbit-mq-service
    container_name: "rabbitmq"
    expose:
      - "5672"
    networks:
      - internal
    ports:
      - "5672:5672"
  dc7101:
    image: "dc7101"
    environment:
      RABBITMQ_HOST: "vro-api-rabbit-mq-service"
    networks:
      - internal


networks:
  internal:
