apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-redis
  labels: {{- toYaml .Values.labels.redis.global | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- toYaml .Values.labels.redis.global | nindent 6 }}
  template:
    metadata:
      labels: {{- toYaml .Values.labels.redis.pod | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.name }}-ghcr
      containers:
        - name: redis-cache
          image: ghcr.io/department-of-veterans-affairs/abd-vro-internal/mirror-redis:latest
          env:
            - name: REDIS_PLACEHOLDERS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.secretName }}
                  key: {{ .Values.redis.passwordKey }}
          ports:
            - containerPort: {{ .Values.service.redis.sourcePort }}
              protocol: TCP
          command: ["redis-server"]
          args: ["--requirepass", "$(REDIS_PLACEHOLDERS_PASSWORD)"]
          resources: {{- toYaml .Values.resources.redis | nindent 12 }}
