spring:
  main:
    # Disable to avoid "Web application could not be started"
    web-application-type: none
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      jdbc-url: ${POSTGRES_URL}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      schema: ${POSTGRES_SCHEMA}
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

# https://stackoverflow.com/questions/36583185/spring-data-jpa-could-not-initialize-proxy-no-session-with-methods-marke
# Degrades performance but only for this Docker image, which is acceptable
#spring.jpa.properties.hibernate.enable_lazy_load_no_trans: true

# Addresses warning: GroovyTemplateAutoConfiguration : Cannot find template location
spring.groovy.template.check-template-location: false

logging:
  level:
    org.springframework.jdbc.core: INFO # DEBUG
#    org.springframework.jdbc.core.JdbcTemplate: INFO # DEBUG
#    org.springframework.jdbc.core.StatementCreatorUtils: INFO # TRACE
    org.hibernate.SQL: INFO # DEBUG
#    org.type.descriptor.sql.BasicBinder: INFO # TRACE
#    org.hibernate.type.descriptor.sql.BasicBinder: INFO # TRACE

spring.config.import: >
  conf-camel.yml,
  conf-camel-rabbitmq.yml
