name: Deploy application to environment

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Target LHDI environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - qa
        - sandbox
        - prod-test
        - prod

      target_release:
        description: 'Target release tag or SHA'
        required: true
        default: 'latest'
        type: string

  # Allow other workflows to call this one
  workflow_call:
    inputs:
      target_env:
        required: true
        type: string
      target_release:
        required: true
        type: string
env:
  COMMIT_SHA: ${{ inputs.target_release }}
  DEV_KUBE_CONFIG: ${{ secrets.DEV_KUBE_CONFIG }}
  SLACK_BOT_ACCESS_TOKEN_DEVOPS: ${{ secrets.SLACK_BOT_ACCESS_TOKEN_DEVOPS }}
  TARGET_ENV: ${{ inputs.target_env }}

jobs:
  deploy-core-services:
    if: github.repository == 'department-of-veterans-affairs/abd-vro'
    runs-on: ubuntu-latest
    steps:
      - name: "Set up kube config"
        run: |
          mkdir ~/.kube
          if [ "${{ env.TARGET_ENV }}" == "sandbox" ] || [ "${{ env.TARGET_ENV }}" == "dev" ] || [ "${{ env.TARGET_ENV }}" == "qa" ]
          then
            echo -n "${{ secrets.DEV_KUBE_CONFIG }}" | base64 -d > ~/.kube/config
          else
            echo -n "${{ secrets.PROD_KUBE_CONFIG }}" | base64 -d > ~/.kube/config
          fi
      - name: "Checkout source code"
        uses: actions/checkout@v3

      - name: "Deploy core to ${{ env.TARGET_ENV }} env"
        run: |
          ./scripts/deploy-app.sh ${{ env.TARGET_ENV }} ${{ env.COMMIT_SHA }}
